name: CI Pipeline

# Trigger the workflow on pull requests and pushes to the main branch
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest

  build:  
  needs: test # Only run if the 'test' job succeeds  
  runs-on: ubuntu-latest  

  steps:  
    - uses: actions/checkout@v3  

    - name: Login to DockerHub  
      env:  
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin  

    - name: Build Docker Image  
      run: docker build -t enop7156/hngstagetwoproject .  

    - name: Push Docker Image to DockerHub  
      run: docker push enop7156/hngstagetwoproject:latest